version: '3.8'
services:
  db:
    image: postgres:16
    env_file:
      - .env.docker
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build: ./weddinggallery
    env_file:
      - .env.docker
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - photos:/photos
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
volumes:
  db-data:
  photos:
